name: Build llama.cpp CUDA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone llama.cpp
        run: |
          git clone https://github.com/ggml-org/llama.cpp.git

      - name: Install build tools and CUDA
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential nvidia-cuda-toolkit

      - name: Configure llama.cpp with CUDA
        run: |
          cmake -S llama.cpp -B llama.cpp/build \
            -DGGML_CUDA=ON

      - name: Build llama.cpp
        run: |
          cmake --build llama.cpp/build --config Release -j2

      - name: Check llama-cli
        run: |
          ./llama.cpp/build/bin/llama-cli --version
